# Generated by Django 3.1.4 on 2020-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(verbose_name=range(1, 5)),
        ),
    ]
