# Generated by Django 3.1.4 on 2021-01-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
