# Generated by Django 3.1.4 on 2020-12-10 14:34

import account.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/')),
                ('address', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=11, validators=[account.validations.phone_validation])),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.CharField(choices=[('None', 'None'), ('سباك', 'سباك'), ('نجار', 'نجار'), ('كهربائى', 'كهربائى'), ('مبيض محاره', 'مبيض محاره')], default='None', max_length=50)),
                ('available', models.BooleanField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_stuff', models.BooleanField(default=False)),
                ('is_technical', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
