# Generated by Django 3.1.4 on 2020-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201210_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
