# Generated by Django 3.1.4 on 2021-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210102_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_technical',
            field=models.BooleanField(default=False),
        ),
    ]
