# Generated by Django 3.1.4 on 2021-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_is_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_technical',
            field=models.BooleanField(default=False),
        ),
    ]
